service: bookstore-app # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
functions:
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: books # path will be domain.name.com/dev/notes
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: books/{id} # path will be domain.name.com/dev/notes/1
          method: get
          cors: true
  getAll:
    handler: handler.getAll # path will be domain.name.com/dev/notes
    events:
      - http:
          path: books
          method: get
          cors: true
  update:
    handler: handler.update # path will be domain.name.com/dev/notes/1
    events:
      - http:
          path: books/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: books/{id} # path will be domain.name.com/dev/notes/1
          method: delete
          cors: true