service: bookstore-app # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
functions:
  createBook:
    handler: bookHandler.create # point to exported create function in handler.js
    events:
      - http:
          path: books # path will be domain.name.com/dev/notes
          method: post
          cors: true
  getOneBook:
    handler: bookHandler.getOne
    events:
      - http:
          path: books/{id} # path will be domain.name.com/dev/notes/1
          method: get
          cors: true
  getAllBook:
    handler: bookHandler.getAll # path will be domain.name.com/dev/notes
    events:
      - http:
          path: books
          method: get
          cors: true
  updateBook:
    handler: bookHandler.update # path will be domain.name.com/dev/notes/1
    events:
      - http:
          path: books/{id}
          method: put
          cors: true
  deleteBook:
    handler: bookHandler.delete
    events:
      - http:
          path: books/{id} # path will be domain.name.com/dev/notes/1
          method: delete
          cors: true
# Order
  createOrder:
    handler: orderHandler.create # point to exported create function in handler.js
    events:
      - http:
          path: orders # path will be domain.name.com/dev/notes
          method: post
          cors: true
  getOneOrder:
    handler: orderHandler.getOne
    events:
      - http:
          path: orders/{id} # path will be domain.name.com/dev/notes/1
          method: get
          cors: true
  getAllOrder:
    handler: orderHandler.getAll # path will be domain.name.com/dev/notes
    events:
      - http:
          path: orders
          method: get
          cors: true
  updateOrder:
    handler: orderHandler.update # path will be domain.name.com/dev/notes/1
    events:
      - http:
          path: orders/{id}
          method: put
          cors: true
  deleteOrder:
    handler: orderHandler.delete
    events:
      - http:
          path: orders/{id} # path will be domain.name.com/dev/notes/1
          method: delete
          cors: true